FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    clang \
    curl \
    file \
    git \
    lcov \
    llvm \
    shellcheck \
    vim \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENTRYPOINT ["tail", "-f", "/dev/null"]