FROM alpine:3.21.3

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk update && apk add --no-cache \
    bash \
    vim \
    clang \
    llvm \
    shellcheck \
    git \
    lcov

WORKDIR /app
VOLUME /app/files

ENTRYPOINT ["tail", "-f", "/dev/null"]