# syntax=docker/dockerfile:latest
FROM ubuntu:22.04

RUN echo -e '\n# Auto-Warpify\nprintf '\''\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "bash", "uname": "Linux" }}\x9c'\'' ' >> ~/.bashrc

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \ 
    apt-get update \
    && apt-get install -y --no-install-recommends \
    clang \
    curl \
    file \
    git \
    lcov \
    llvm \
    shellcheck \
    vim \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENTRYPOINT ["tail", "-f", "/dev/null"]