# syntax=docker/dockerfile:latest
FROM alpine:3.21.3

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk update && apk add --no-cache \
    bash \
    clang \
    curl \
    file \
    git \
    llvm \
    lcov \
    shellcheck \
    vim \
    wget

# Auto warpify for Warp Terminal
COPY scripts/warpify.sh /usr/local/bin/warpify.sh
RUN chmod +x /usr/local/bin/warpify.sh && /usr/local/bin/warpify.sh

WORKDIR /app
ENTRYPOINT ["tail", "-f", "/dev/null"]
