# syntax=docker/dockerfile:latest

FROM ubuntu:24.10 AS base

COPY scripts/install_deps.sh /usr/local/bin/install_deps.sh
RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    bash /usr/local/bin/install_deps.sh

####################################

FROM base AS warpify

# Auto warpify for Warp Terminal
COPY scripts/warpify.sh /usr/local/bin/warpify.sh
RUN chmod +x /usr/local/bin/warpify.sh && /usr/local/bin/warpify.sh

####################################

FROM warpify AS final

WORKDIR /app
ENTRYPOINT ["tail", "-f", "/dev/null"]
